const MESSAGES = {
    COMMANDS: {
        INFORMATIONS: {
            HELP: {
                name: 'help',
                aliases: ['help', 'h', 'aide'],
                category: 'informations',
                description: 'Renvoie une liste de commandes avec leurs informations.',
                cooldown: 0,
                usage: '<command_name>',
                needUser: false,
                applicableOnModerator: false,
                public: true,
                args: false,
            },

            USERINFO: {
                name: 'userinfo',
                aliases: ['userinfo', 'infouser'],
                category: 'informations',
                description: 'Renvoie les informations de l\'utilisateur mentionné.',
                cooldown: 10,
                usage: '<mention_utilisateur>',
                needUser: true,
                applicableOnModerator: true,
                public: true,
                args: true,
            },
        },

        MISC: {
            PING: {
                name: 'ping',
                aliases: ['ping'],
                category: 'misc',
                description: 'Renvoie pong !',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnModerator: true,
                public: true,
                args: false,
            },
            
            ROLL: {
                name: 'roll',
                aliases: ['roll'],
                category: 'misc',
                description: 'Lance des dés',
                cooldown: 1,
                usage: " : nombre aléatoire entre 1 et 6\n§roll <int> : nombre aléatoire entre 1 et <int>\n§roll <int1> <int2> : nombre aléatoire entre <int1> et <int2>",
                needUser: false,
                applicableOnModerator: true,
                public: true,
                args: false,
            },

            SAY: {
                name: 'say',
                aliases: ['say', 'repeat', 'rep'],
                category: 'misc',
                description: 'Fait parler BabyPengu',
                cooldown: 0,
                usage: `<message>`,
                needUser: false,
                applicableOnModerator: true,
                public: true,
                args: true,
            },
        },

        MODERATION: {
            ADD: {
                name: 'add',
                aliases: ['add'],
                category: 'moderation',
                description: 'Ajoute un ou plusieurs rôles.',
                cooldown: 0,
                usage: '<role> : ajoute un rôle\n$add <role> ... <role> : ajoute tous les rôles passés en paramètre',
                needUser: false,
                applicableOnModerator: true,
                public: true,
                args: true,
            },

            BAN: {
                name: 'ban',
                aliases: ['ban'],
                category: 'moderation',
                description: 'Ban un utilisateur',
                cooldown: 0,
                usage: `<@utilisateur> <raison>`,
                needUser: true,
                applicableOnModerator: false,
                public: false,
                args: true,
            },

            KICK: {
                name: 'kick',
                aliases: ['kick'],
                category: 'moderation',
                description: 'Kick un utilisateur',
                cooldown: 0,
                usage: `<@utilisateur> <raison>`,
                needUser: true,
                applicableOnModerator: false,
                public: false,
                args: true,
            },

            MUTE: {
                name: 'mute',
                aliases: ['mute', 'ftg'],
                category: 'moderation',
                description: 'Mute un utilisateur',
                cooldown: 0,
                usage: `<@utilisateur> <temps>`,
                needUser: true,
                applicableOnModerator: false,
                public: false,
                args: true,
            },

            PRUNE: {
                name: 'prune',
                aliases: ['prune'],
                category: 'moderation',
                description: 'Purge un nombre de messages spécifié sur un utilisateur spécifié',
                cooldown: 5,
                usage: `<@utilisateur> <nombre_de_messages>`,
                needUser: true,
                applicableOnModerator: false,
                public: false,
                args: true,
            },

            PURGE: {
                name: 'purge',
                aliases: ['purge'],
                category: 'moderation',
                description: 'Purge un nombre de messages spécifié',
                cooldown: 5,
                usage: `<nombre_de_messages>`,
                needUser: false,
                applicableOnModerator: true,
                public: false,
                args: true,
            },
            
            REMOVE: {
                name: 'remove',
                aliases: ['remove'],
                category: 'moderation',
                description: 'Retire un ou plusieurs rôles.',
                cooldown: 0,
                usage: '<role> : retire le rôle\n$remove <role> ... <role> : retire tous les rôles passés en paramètre',
                needUser: false,
                applicableOnModerator: true,
                public: true,
                args: true,
            },

            UNBAN: {
                name: 'unban',
                aliases: ['unban'],
                category: 'moderation',
                description: 'Unban un utilisateur',
                cooldown: 0,
                usage: `<id_utilisateur>`,
                needUser: true,
                applicableOnModerator: false,
                public: false,
                args: true,
            },

            UNMUTE: {
                name: 'unmute',
                aliases: ['unmute'],
                category: 'moderation',
                description: 'Unmute un utilisateur',
                cooldown: 0,
                usage: `<@utilisateur>`,
                needUser: true,
                applicableOnModerator: false,
                public: true,
                args: true,
            },
        },

        REACTIONS: {
            ALLROLES: {
                name: 'allroles',
                aliases: ['allroles'],
                category: 'reactions',
                description: 'Renvoie un message avec des reactions',
                cooldown: 0,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                public: false,
                args: false,
            },

            LOBBY: {
                name: 'lobby',
                aliases: ['lobby', 'acceuil'],
                category: 'reactions',
                description: 'Renvoie le message d\'acceuil du serveur',
                cooldown: 0,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                public: false,
                args: false,
            },
        },
    },
};

exports.MESSAGES = MESSAGES;