const MESSAGES = {
    COMMANDS: {
        ADMIN: {
            CONFIG: {
                name: 'config',
                aliases: ['config'],
                category: 'admin',
                description: 'Modifie la base de données.',
                cooldown: 0,
                usage: '<key> : affiche la valeur de <key>\n. . . . . . . .<key> <new_value> : change la valeur de <key>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel:9,
                args: true,
            },

            EVAL: {
                name: 'eval',
                aliases: ['eval'],
                category: 'admin',
                description: 'Evalue un code javascript.',
                cooldown: 0,
                usage: '<code_to_test>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 10,
                args: true,
            },

            RELOAD: {
                name: 'reload',
                aliases: ['reload'],
                category: 'admin',
                description: 'Relance le bot.',
                cooldown: 0,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 9,
                args: false,
            },
        },

        CHANNELS: {
            ADDACCESS: {
                name: 'addaccess',
                aliases: ['addaccess'],
                category: 'channels',
                description: 'Authorise les utilisateurs mentionnés à accéder au salon courant.',
                cooldown: 5,
                usage: `<@user / @roles>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

            ADDSUPERACCESS: {
                name: 'addsuperaccess',
                aliases: ['addsuperaccess'],
                category: 'channels',
                description: 'Authorise les utilisateurs mentionnés à modérer le salon courant.',
                cooldown: 5,
                usage: `<@user / @roles>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

            DELETECHANNEL: {
                name: 'deletechannel',
                aliases: ['deletechannel'],
                category: 'channels',
                description: 'Supprime le salon textuel courant ( et les salons vocaux associés s\'ils existent ).',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 8,
                args: false,
            },

            NEWLINKEDCHANNEL: {
                name: 'newlinkedchannel',
                aliases: ['newlinkedchannel'],
                category: 'channels',
                description: 'Crée un channel textuel jumeau au channel courant.',
                cooldown: 0,
                usage: `<name>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

            NEWPRIVATECHANNEL: {
                name: 'newprivatechannel',
                aliases: ['newprivatechannel'],
                category: 'channels',
                description: 'Crée un channel privé dans une certaine catégorie.',
                cooldown: 5,
                usage: `<category_id> <name>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

            NEWVOICECHANNEL: {
                name: 'newvoicechannel',
                aliases: ['newvoicechannel'],
                category: 'channels',
                description: 'Crée un channel vocal associé au channel courant.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: false,
            },

            REMOVEACCESS: {
                name: 'removeaccess',
                aliases: ['removeaccess'],
                category: 'channels',
                description: 'Empêche les utilisateurs mentionnés d\'accéder au salon courant.',
                cooldown: 5,
                usage: `<@users / @roles>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },
        },

        COLLECTORS: {
            MSGCOLLECTOR: {
                name: 'msgcollector',
                aliases: ['msgcollector', 'msgcol', 'mcol'],
                category: 'collectors',
                description: 'Compte l\'oocurence d\'un message.',
                cooldown: 10,
                usage: '<msg_to_collect>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 1,
                args: true,
            },

            REACTCOLLECTOR: {
                name: 'reactcollector',
                aliases: ['reactcollector', 'reactcol', 'rcol'],
                category: 'collectors',
                description: 'Compte les réactions.',
                cooldown: 10,
                usage: '<reaction_to_collect>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 1,
                args: true,
            },
        },

        EXPERIENCE: {
            ADDEXPERIENCE: {
                name: 'addexperience',
                aliases: ['addexperience', 'addexp', 'addxp'],
                category: 'experience',
                description: "Ajoute de l'experience à l'utilisateur mentionné.",
                cooldown: 5,
                usage: '<@user> <exp_to_add>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 9,
                args: false,
            },

            LEADERBOARD: {
                name: 'leaderboard',
                aliases: ['leaderboard', 'xpboard', 'expboard', 'board'],
                category: 'experience',
                description: "Affiche le classement des joueurs.",
                cooldown: 5,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            REMOVEEXPERIENCE: {
                name: 'removeexperience',
                aliases: ['removeexperience', 'removeexp', 'removexp'],
                category: 'experience',
                description: "Retire de l'experience à l'utilisateur mentionné.",
                cooldown: 5,
                usage: '<@user> <exp_to_remove>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 9,
                args: false,
            },

            USEREXPERIENCE: {
                name: 'userexperience',
                aliases: ['userexperience', 'userexp', 'userxp'],
                category: 'experience',
                description: "Renvoie l'experience de l'utilisateur.",
                cooldown: 0,
                usage: `: affiche votre experience\n. . . . . . . . . . . . . . . . <@user> : affiche l'experience de l'utilisateur mentionné`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },
        },

        GAMES: {
            CARD: {
                name: 'card',
                aliases: ['card'],
                category: 'games',
                description: 'Renvoie une carte.',
                cooldown: 0,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            RPC: {
                name: 'rpc',
                aliases: ['rpc', 'pfc', 'chifoumi'],
                category: 'games',
                description: 'Joue une manche de pierre feuille ciseaux avec toi.',
                cooldown: 0,
                usage: '<Pierre/Feuille/Ciseaux>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: true,
            },
        },

        INFORMATIONS: {
            BOTINFO: {
                name: 'botinfo',
                aliases: ['botinfo', 'infobot'],
                category: 'informations',
                description: 'Renvoie des informations sur le bot',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            HELP: {
                name: 'help',
                aliases: ['help', 'h', 'aide', 'aled', 'oskour'],
                category: 'informations',
                description: 'Renvoie une liste de commandes avec leurs informations.',
                cooldown: 0,
                usage: '<command_name> : renvoie des informations sur <command_name>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            SERVERINFO: {
                name: 'serverinfo',
                aliases: ['serverinfo', 'infoserver', 'infoserv', 'servinfo'],
                category: 'informations',
                description: 'Renvoie des informations sur le serveur.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            STATS: {
                name: 'stats',
                aliases: ['stats'],
                category: 'informations',
                description: 'Renvoie des statistiques sur le serveur.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            USERINFO: {
                name: 'userinfo',
                aliases: ['userinfo', 'infouser', 'uinfo', 'infou'],
                category: 'informations',
                description: "Renvoie des informations sur l'utilisateur.",
                cooldown: 5,
                usage: `<@user>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },
        },

        MISC: {
            ASK: {
                name: 'ask',
                aliases: ['ask', 'question', 'dispengu'],
                category: 'misc',
                description: 'Répond à une question.',
                cooldown: 5,
                usage: `<question>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: true,
            },

            BIRTHDAY: {
                name: 'birthday',
                aliases: ['birthday', 'anniversaire', 'anniv'],
                category: 'misc',
                description: 'Ajoute, supprime ou annonce la date d\'anniversaire d\'un utilisateur mentionné',
                cooldown: 5,
                usage: `set <@user> <ddmm>\n. . . . . . . . . .del <@user>\n. . . . . . . . . .of <@user>`,
                needUser: true,
                applicableOnSuperior: true,
                permLevel: 0,
                args: true,
            },

            CONTACT: {
                name: 'contact',
                aliases: ['contact', 'idc', 'iledechybre'],
                category: 'misc',
                description: 'Renvoie les contacts de l\'Ile de Chybre.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            MATH: {
                name: 'math',
                aliases: ['math'],
                category: 'misc',
                description: 'Fais des calculs pour vous.',
                cooldown: 5,
                usage: '<calcul>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: true,
            },

            PING: {
                name: 'ping',
                aliases: ['ping'],
                category: 'misc',
                description: 'Renvoie pong !',
                cooldown: 5,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            ROLL: {
                name: 'roll',
                aliases: ['roll', 'de'],
                category: 'misc',
                description: 'Lance des dés.',
                cooldown: 0,
                usage: `: nombre aléatoire entre 1 et 6\n. . . . . <int> : nombre aléatoire entre 1 et <int>\n. . . . . <int1> <int2> : nombre aléatoire entre <int1> et <int2>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 0,
                args: false,
            },

            SAY: {
                name: 'say',
                aliases: ['say', 'repeat', 'rep'],
                category: 'misc',
                description: 'Fait parler BabyPengu.',
                cooldown: 0,
                usage: `<message>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 1,
                args: true,
            },

            VOTE: {
                name: 'vote',
                aliases: ['vote', 'sondage'],
                category: 'misc',
                description: 'Crée un sondage.',
                cooldown: 0,
                usage: '<question>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 1,
                args: true,
            },
        },

        MODERATION: {
            BAN: {
                name: 'ban',
                aliases: ['ban'],
                category: 'moderation',
                description: 'Ban un utilisateur.',
                cooldown: 5,
                usage: `<@user> <reason> : ban <@utilisateur> pour <raison>`,
                needUser: true,
                applicableOnSuperior: false,
                permLevel: 7,
                args: true,
            },

            KICK: {
                name: 'kick',
                aliases: ['kick'],
                category: 'moderation',
                description: 'Kick un utilisateur.',
                cooldown: 5,
                usage: `<@user> <raison> : éjecte <@utilisateur> pour <raison>`,
                needUser: true,
                applicableOnSuperior: false,
                permLevel: 7,
                args: true,
            },

            MUTE: {
                name: 'mute',
                aliases: ['mute', 'ftg'],
                category: 'moderation',
                description: 'Mute un utilisateur.',
                cooldown: 5,
                usage: `<@user> <time> : mute <@user> pour une durée de <time>`,
                needUser: true,
                applicableOnSuperior: false,
                permLevel: 5,
                args: true,
            },

            PRUNE: {
                name: 'prune',
                aliases: ['prune'],
                category: 'moderation',
                description: 'Purge un nombre de messages spécifié sur un utilisateur spécifié.',
                cooldown: 5,
                usage: `<@utilisateur> <int> : supprime <int> messages de <@utilisateur>`,
                needUser: true,
                applicableOnSuperior: false,
                permLevel: 5,
                args: true,
            },

            PURGE: {
                name: 'purge',
                aliases: ['purge'],
                category: 'moderation',
                description: 'Purge un nombre de messages spécifié.',
                cooldown: 5,
                usage: `<int> : supprime <int> messages`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 5,
                args: true,
            },

            REPORT: {
                name: 'report',
                aliases: ['report'],
                category: 'moderation',
                description: 'Report un utilisateur.',
                cooldown: 5,
                usage: `<@utilisateur> [message_id] [reason]`,
                needUser: true,
                applicableOnSuperior: true,
                permLevel: 1,
                args: true,
            },

            SETPERMISSIONLEVEL: {
                name: 'setpermissionlevel',
                aliases: ['setpermissionlevel', 'setperms'],
                category: 'moderation',
                description: 'Change le degré de permissions des utilisateurs passés en paramètre.',
                cooldown: 5,
                usage: `<@utilisateurs> <0-10>`,
                needUser: true,
                applicableOnSuperior: true,
                permLevel: 6,
                args: true,
            },

            UNBAN: {
                name: 'unban',
                aliases: ['unban', 'deban'],
                category: 'moderation',
                description: 'Unban un utilisateur.',
                cooldown: 5,
                usage: `<user_id>`,
                needUser: false,
                applicableOnSuperior: false,
                permLevel: 7,
                args: true,
            },

            UNMUTE: {
                name: 'unmute',
                aliases: ['unmute', 'demute'],
                category: 'moderation',
                description: 'Unmute un utilisateur.',
                cooldown: 5,
                usage: `<@user>`,
                needUser: true,
                applicableOnSuperior: false,
                permLevel: 5,
                args: true,
            },
        },

        REACTIONS: {
            ALLROLES: {
                name: 'allroles',
                aliases: ['allroles'],
                category: 'reactions',
                description: 'Renvoie un message avec des reactions.',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 10,
                args: false,
            },

            EMOJI: {
                name: 'emoji',
                aliases: ['emoji'],
                category: 'reactions',
                description: 'Renvoie des emojis sur notre message.',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 10,
                args: false,
            },

            LOBBY: {
                name: 'lobby',
                aliases: ['lobby', 'acceuil'],
                category: 'reactions',
                description: 'Renvoie le message d\'acceuil du serveur',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 10,
                args: false,
            },
        },

        ROLES: {
            ADDROLE: {
                name: 'addrole',
                aliases: ['addrole'],
                category: 'roles',
                description: 'Ajoute un ou plusieurs rôles.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

            CREATEROLE: {
                name: 'createrole',
                aliases: ['createrole', 'creerrole', 'newrole'],
                category: 'roles',
                description: 'Crée un rôle.',
                cooldown: 5,
                usage: `<name> : crée le rôle <name>\n. . . . . . . . . . . <name> <color> : crée le rôle <name> de couleur <color>`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

            DELETEROLE: {
                name: 'deleterole',
                aliases: ['deleterole'],
                category: 'roles',
                description: 'Supprime un ou plusieurs rôles.',
                cooldown: 5,
                usage: '<role_names>',
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 8,
                args: true,
            },
            
            REMOVEROLE: {
                name: 'removerole',
                aliases: ['removerole'],
                category: 'roles',
                description: 'Retire un ou plusieurs rôles.',
                cooldown: 5,
                usage: `<role_name> ... <role_name> : retire tous les rôles passés en paramètre`,
                needUser: false,
                applicableOnSuperior: true,
                permLevel: 3,
                args: true,
            },

        },
    },
};

exports.MESSAGES = MESSAGES;
