const MESSAGES = {
    COMMANDS: {
        ADMIN: {
            CONFIG: {
                name: 'config',
                aliases: ['config'],
                category: 'admin',
                description: 'Modifie la base de données.',
                cooldown: 0,
                usage: '<key> : affiche la valeur de <key>\n. . . . . . . .<key> <new_value> : change la valeur de <key>',
                needUser: false,
                applicableOnModerator: false,
                modo: false,
                public: false,
                args: true,
            },

            EVAL: {
                name: 'eval',
                aliases: ['eval'],
                category: 'admin',
                description: 'Evalue un code javascript.',
                cooldown: 0,
                usage: '<code_to_test>',
                needUser: false,
                applicableOnModerator: false,
                modo: false,
                public: false,
                args: true,
            },

            RELOAD: {
                name: 'reload',
                aliases: ['reload'],
                category: 'admin',
                description: 'Relance le bot.',
                cooldown: 0,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: false,
                public: false,
                args: false,
            },
        },

        COLLECTORS: {
            MSGCOLLECTOR: {
                name: 'msgcollector',
                aliases: ['msgcollector', 'msgcol', 'mcol'],
                category: 'collectors',
                description: 'Compte l\'oocurence d\'un message.',
                cooldown: 10,
                usage: '<msg_to_collect>',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            REACTCOLLECTOR: {
                name: 'reactcollector',
                aliases: ['reactcollector', 'reactcol', 'rcol'],
                category: 'collectors',
                description: 'Compte les réactions.',
                cooldown: 10,
                usage: '<reaction_to_collect>',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: false,
            },
        },

        EXPERIENCE: {
            ADDEXPERIENCE: {
                name: 'addexperience',
                aliases: ['addexperience', 'addexp', 'addxp'],
                category: 'experience',
                description: "Ajoute de l'experience à l'utilisateur mentionné.",
                cooldown: 5,
                usage: '<@user> <exp_to_add>',
                needUser: true,
                applicableOnModerator: true,
                modo: true,
                public: false,
                args: true,
            },

            LEADERBOARD: {
                name: 'leaderboard',
                aliases: ['leaderboard', 'xpboard', 'expboard', 'board'],
                category: 'experience',
                description: "Affiche le classement des joueurs.",
                cooldown: 5,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },

            REMOVEEXPERIENCE: {
                name: 'removeexperience',
                aliases: ['removeexperience', 'removeexp', 'removexp'],
                category: 'experience',
                description: "Retire de l'experience à l'utilisateur mentionné.",
                cooldown: 5,
                usage: '<@user> <exp_to_remove>',
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            USEREXPERIENCE: {
                name: 'userexperience',
                aliases: ['userexperience', 'userexp', 'userxp'],
                category: 'experience',
                description: "Renvoie l'experience de l'utilisateur.",
                cooldown: 0,
                usage: `: affiche votre experience\n. . . . . . . . . . . . . . . . <@user> : affiche l'experience de l'utilisateur`,
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },
        },

        GAMES: {
            CARD: {
                name: 'card',
                aliases: ['card'],
                category: 'games',
                description: 'Renvoie une carte.',
                cooldown: 0,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },
        },

        INFORMATIONS: {
            BOTINFO: {
                name: 'botinfo',
                aliases: ['botinfo', 'infobot'],
                category: 'informations',
                description: 'Renvoie des informations sur le bot',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },

            HELP: {
                name: 'help',
                aliases: ['help', 'h', 'aide'],
                category: 'informations',
                description: 'Renvoie une liste de commandes avec leurs informations.',
                cooldown: 0,
                usage: '<command_name> : renvoie des informations sur <command_name>',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },

            SERVERINFO: {
                name: 'serverinfo',
                aliases: ['serverinfo', 'infoserver', 'infoserv', 'servinfo'],
                category: 'informations',
                description: 'Renvoie des informations sur le serveur.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },

            STATS: {
                name: 'stats',
                aliases: ['stats'],
                category: 'informations',
                description: 'Renvoie des statistiques sur le serveur.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },

            USERINFO: {
                name: 'userinfo',
                aliases: ['userinfo', 'infouser', 'uinfo', 'infou'],
                category: 'informations',
                description: "Renvoie des informations sur l'utilisateur.",
                cooldown: 5,
                usage: `<@user>`,
                needUser: true,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },
        },

        MISC: {
            ASK: {
                name: 'ask',
                aliases: ['ask', 'question', 'dispengu'],
                category: 'misc',
                description: 'Répond à une question.',
                cooldown: 5,
                usage: `<question>`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },

            CONTACT: {
                name: 'contact',
                aliases: ['contact', 'idc', 'iledechybre'],
                category: 'misc',
                description: 'Renvoie les contacts de l\'Ile de Chybre.',
                cooldown: 5,
                usage: ``,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: false,
            },

            MATH: {
                name: 'math',
                aliases: ['math'],
                category: 'misc',
                description: 'Fais des calculs pour vous.',
                cooldown: 5,
                usage: '<calcul>',
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },

            PING: {
                name: 'ping',
                aliases: ['ping'],
                category: 'misc',
                description: 'Renvoie pong !',
                cooldown: 5,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: true,
                args: false,
            },

            POLL: {
                name: 'poll',
                aliases: ['poll', 'sondage'],
                category: 'misc',
                description: 'Crée un sondage.',
                cooldown: 5,
                usage: '<question>',
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },
            
            ROLL: {
                name: 'roll',
                aliases: ['roll', 'de'],
                category: 'misc',
                description: 'Lance des dés.',
                cooldown: 0,
                usage: `: nombre aléatoire entre 1 et 6\n. . . . . <int> : nombre aléatoire entre 1 et <int>\n. . . . . <int1> <int2> : nombre aléatoire entre <int1> et <int2>`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: false,
            },

            SAY: {
                name: 'say',
                aliases: ['say', 'repeat', 'rep'],
                category: 'misc',
                description: 'Fait parler BabyPengu.',
                cooldown: 0,
                usage: `<message>`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },
        },

        MODERATION: {
            ADD: {
                name: 'add',
                aliases: ['add', 'addrole'],
                category: 'moderation',
                description: 'Ajoute un ou plusieurs rôles.',
                cooldown: 5,
                usage: `<role_name> ... <role_name> : ajoute les rôles passés en paramètre`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },

            ADDACCESS: {
                name: 'addaccess',
                aliases: ['addaccess'],
                category: 'moderation',
                description: 'Authorise les utilisateurs mentionnés à accéder au salon courant.',
                cooldown: 5,
                usage: `<@user>`,
                needUser: true,
                applicableOnModerator: true,
                modo: true,
                public: false,
                args: true,
            },

            ADDTO: {
                name: 'addto',
                aliases: ['addto', 'addroleto'],
                category: 'moderation',
                description: 'Ajoute un ou plusieurs rôles à un utilisateur mentionné.',
                cooldown: 5,
                usage: `<@user> <role_name> ... <role_name> : ajoute les rôles à l\'utilisateur`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            BAN: {
                name: 'ban',
                aliases: ['ban'],
                category: 'moderation',
                description: 'Ban un utilisateur.',
                cooldown: 5,
                usage: `<@user> <reason> : ban <@utilisateur> pour <raison>`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            CREATEROLE: {
                name: 'createrole',
                aliases: ['createrole', 'creerrole', 'newrole'],
                category: 'moderation',
                description: 'Crée un rôle.',
                cooldown: 5,
                usage: `<name> : crée le rôle <name>\n. . . . . . . . . . . <name> <color> : crée le rôle <name> de couleur <color>`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: false,
                args: true,
            },

            KICK: {
                name: 'kick',
                aliases: ['kick'],
                category: 'moderation',
                description: 'Kick un utilisateur.',
                cooldown: 5,
                usage: `<@user> <raison> : éjecte <@utilisateur> pour <raison>`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            MUTE: {
                name: 'mute',
                aliases: ['mute', 'ftg'],
                category: 'moderation',
                description: 'Mute un utilisateur.',
                cooldown: 5,
                usage: `<@user> <time> : mute <@user> pour une durée de <time>`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            NEWPRIVATECHANNEL: {
                name: 'newprivatechannel',
                aliases: ['newprivatechannel'],
                category: 'moderation',
                description: 'Crée un channel privé dans une certaine catégorie.',
                cooldown: 5,
                usage: `<category_id> <name>`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: false,
                args: true,
            },

            PRUNE: {
                name: 'prune',
                aliases: ['prune'],
                category: 'moderation',
                description: 'Purge un nombre de messages spécifié sur un utilisateur spécifié.',
                cooldown: 5,
                usage: `<@user> <int> : supprime <int> messages de <@utilisateur>`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            PURGE: {
                name: 'purge',
                aliases: ['purge'],
                category: 'moderation',
                description: 'Purge un nombre de messages spécifié.',
                cooldown: 5,
                usage: `<int> : supprime <int> messages`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: false,
                args: true,
            },
            
            REMOVE: {
                name: 'remove',
                aliases: ['remove', 'removerole'],
                category: 'moderation',
                description: 'Retire un ou plusieurs rôles.',
                cooldown: 5,
                usage: `<role_name> ... <role_name> : retire tous les rôles passés en paramètre`,
                needUser: false,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },

            REMOVEACCESS: {
                name: 'removeaccess',
                aliases: ['removeaccess'],
                category: 'moderation',
                description: 'Empêche les utilisateurs mentionnés d\'accéder au salon courant.',
                cooldown: 5,
                usage: `<@users>`,
                needUser: true,
                applicableOnModerator: true,
                modo: true,
                public: false,
                args: true,
            },

            REMOVEFROM: {
                name: 'removefrom',
                aliases: ['removefrom', 'removerolefrom'],
                category: 'moderation',
                description: 'Retire un ou plusieurs rôles à un utilisateur mentionné.',
                cooldown: 5,
                usage: `<@user> <role> ... <role> : retire tous les rôles passés en paramètre à l\'utilisateur`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            REPORT: {
                name: 'report',
                aliases: ['report'],
                category: 'moderation',
                description: 'Report un utilisateur.',
                cooldown: 5,
                usage: `<@user> [message_id] [reason]`,
                needUser: true,
                applicableOnModerator: true,
                modo: true,
                public: true,
                args: true,
            },

            UNBAN: {
                name: 'unban',
                aliases: ['unban', 'deban'],
                category: 'moderation',
                description: 'Unban un utilisateur.',
                cooldown: 5,
                usage: `<user_id>`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },

            UNMUTE: {
                name: 'unmute',
                aliases: ['unmute', 'demute'],
                category: 'moderation',
                description: 'Unmute un utilisateur.',
                cooldown: 5,
                usage: `<@user>`,
                needUser: true,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: true,
            },
        },

        REACTIONS: {
            ALLROLES: {
                name: 'allroles',
                aliases: ['allroles'],
                category: 'reactions',
                description: 'Renvoie un message avec des reactions.',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: false,
            },

            EMOJI: {
                name: 'emoji',
                aliases: ['emoji'],
                category: 'reactions',
                description: 'Renvoie des emojis sur notre message.',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: false,
            },

            LOBBY: {
                name: 'lobby',
                aliases: ['lobby', 'acceuil'],
                category: 'reactions',
                description: 'Renvoie le message d\'acceuil du serveur',
                cooldown: 10,
                usage: '',
                needUser: false,
                applicableOnModerator: false,
                modo: true,
                public: false,
                args: false,
            },
        },
    },
};

exports.MESSAGES = MESSAGES;